FROM eclipse-temurin:17-jdk

WORKDIR /app


COPY pom.xml .
COPY src ./src



RUN apk add --no-cache maven && \
    mvn dependency:go-offline && \
    mvn clean package -DskipTests

    CMD ["java", "-jar", "target/university-guide-1.0.0.jar"]
